# Generated by Django 5.1.6 on 2025-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
